#pragma once

#include <stdbool.h>
#include <stdio.h>
#define FSAVE_STATE_TWO                  "m_state_tw"
#define FMISSION_2                       "mission_2"
#define MISSION_TWO_HACKED               "m2pwnd"
#define MISSION_TWO_YWHACK_COMPLETE      "m2ywhack"
#define MISSION_TWO_EC_COMPLETE          "m2ec"    // Mission with EC startedidf
#define FMISSION_TYPE                    "m_type"  // 0 = EC, 1 = YWHACK
#define MISSION_TWO_CAR_BEACON           71
#define MISSION_TWO_RED_HACK_BEACON      39
#define MISSION_TWO_YWHACK_BEACONHACKED  38
#define MISSION_TWO_YWHACK_BEACON        32
#define MISSION_TWO_YWHACK_DESCR         23
#define MISSION_TWO_DESCRIPTION          19
#define MISSION_TWO_EC_HACKED_BEACON     121
#define MISSION_TWO_EC_BEACON            121
#define MISSION_TWO_EC_MISSION_AS        76
#define MISSION_TWO_EC_DESCRIPTION       12
#define MISSION_TWO_EC_ASA_BEACON        62
#define MISSION_TWO_EC_ASA_BEACON_HACKED 62
#define MISSION_TWO_EC_ASA_DESCR         15
typedef enum {
  MISSION_TWO_YWH_IDLE,    // Waiting for a beacon in the patagonspace village
  MISSION_TWO_RED_HACKED,  // Show mission
  MISSION_TWO_CAR_BEACON_IDLE,
  MISSION_TWO_SHOW_MISSION,
  MISSION_TWO_EC_BEACON_IDLE,
  MISSION_TWO_EC_BEACON_START,
  MISSION_TWO_ASA_BEACON_IDLE,
  MISSION_TWO_ASA_EC_BEACON_COMPLETE,
} mission_two_state_t;

// 'Screenshot_2024-11-01_at_6', 32x32px
const unsigned char bitmap_michi[] = {
    0x00, 0x00, 0x07, 0xc0, 0x00, 0x00, 0x07, 0xe0, 0x00, 0x00, 0x0d, 0xe0,
    0x00, 0x07, 0xfb, 0xa0, 0x00, 0x1f, 0xbb, 0xf0, 0x3c, 0x74, 0x01, 0xb0,
    0x67, 0xd0, 0x00, 0x58, 0xfd, 0x80, 0x04, 0xf8, 0xfe, 0x01, 0xff, 0xf8,
    0xff, 0x1f, 0xf9, 0xfc, 0x7e, 0x7f, 0xe0, 0xfc, 0x2f, 0xff, 0xe0, 0xfc,
    0x3b, 0x83, 0xe3, 0xfe, 0x1f, 0xc5, 0xff, 0xfe, 0x1f, 0xcf, 0xff, 0xfe,
    0x1b, 0xff, 0xff, 0xfe, 0x1f, 0xff, 0xff, 0xff, 0x15, 0xff, 0xff, 0xfb,
    0x37, 0xff, 0xff, 0xfb, 0x27, 0xff, 0xff, 0xff, 0x23, 0xff, 0xff, 0xff,
    0x27, 0xff, 0xfd, 0xff, 0x4f, 0xff, 0xff, 0xbf, 0x7f, 0xf7, 0xe7, 0xff,
    0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xdf, 0xff, 0xff, 0xff,
    0xdf, 0xff, 0xff, 0xff, 0xcf, 0xff, 0xff, 0xfe, 0x7f, 0xff, 0xff, 0xfe,
    0x0f, 0xff, 0xff, 0xfe, 0x00, 0x3f, 0xff, 0xfc};

char* mission_two_carhacking_beacon[MISSION_TWO_CAR_BEACON] = {
    ".. Tu vehiculo",
    "rueda por la",
    "carreta rajada",
    "tras las",
    "tormentas ...",
    "             ",
    "El cambio de",
    "las condiciones",
    "climaticas ha",
    "provocado las",
    "tormentas, que",
    "en consecuencia",
    "ha traido ",
    "da\32os a la",
    "carretera. ",
    "Pero si ",
    "hubieramos",
    "conducido",
    "menos,",
    "habriamos",
    "tenido menos",
    "impacto vas",
    "pensando en ",
    "voz alta."
    "             ",
    "-No pude",
    "evitar",
    "escucharte..."
    "             ",
    "-Una gran",
    "parte del"
    "problema es",
    "nuestra",
    "dependencia en",
    "la tecnologia ",
    "no optima. ",
    "Si tienes",
    "codigo mal",
    "escrito, tus",
    "servidores",
    "corren por"
    "mas tiempo.",
    "Si no",
    "optimizas,",
    "afecta al ",
    "rendimiento",
    "del sistema."
    "             ",
    "No seria bueno",
    "aprender mas ",
    "sobre como ",
    "corregir esos",
    "errores para",
    "minimizar el",
    "consumo",
    "energetico?",
    "- te preguntas",
    "mientras",
    "buscas a",
    "alguien que",
    "te pueda",
    "echar una"
    "mano a ",
    "comprender ",
    "mejor como",
    "gestionar los",
    "constantes",
    "errores de ",
    "codigo."
    "             ",
    "- En eso",
    "piensas en la",
    "villa de",
    "Yes We Hack",
    "             ",
    "Si, ellos",
    "tambien",
    "hackean ..."};

char* mission_two_red_beacon_hacked[MISSION_TWO_RED_HACK_BEACON] = {
    "Mas cuidado!",  "acabas de ser",   "hackeado!",
    "             ", "Ahora tu badge",  "esta bajo el",
    "control de",    "un ransomware",   "...",
    "             ", "Este ransomware", "entorpece tu",
    "sistema y",     "te muestra",      "texto en",
    "utilizando",    "frases en",       "formato aliado",
    "             ", "Si quieres",      "recuperar el",
    "control de tu", "badge, debes",    "resolver la",
    "mision en la",  "villla de",       "Yes We Hack",
    "             ", "             ",   "O tal vez",
    "alguna otra",   "villa te puede",  "ayudar a",
    "recuperar el",  "control de tu",   "badge...",
    "             ", "No todo es",      "red team...",
};

char* mission_two_ywhack_beacon_hacked[MISSION_TWO_YWHACK_BEACONHACKED] = {
    "Se te acerca",
    "une de les",
    "coleques",
    "hackers, ",
    "te pasa una",
    "tabla de",
    "conversion y",
    "te pide que",
    "le eches una",
    "mano a ",
    "decodificar un",
    "mensaje. ",
    "Pero no es",
    "porque el",
    "colegue no",
    "pueda, sino",
    "porque asi",
    "va la historia",
    "             ",
    "             ",
    "No tienen la",
    "tabla completa,"
    "asi que tienes"
    "que echar mano",
    "de tus",
    "conocimientos en",
    "criptografia",
    "para ",
    "descifrar el",
    "error oculto",
    "en el codigo.",
    "             ",
    "             ",
    "Como pago por",
    "el trabajo, ",
    "te dara un ",
    "add-on para",
    "tu badge.",
    "Y un codigo",
    "para la matrix."};

char* mission_two_ywhack_beacon[MISSION_TWO_YWHACK_BEACON] = {
    "Se te acerca",
    "uno de los",
    "colegas",
    "hackers, ",
    "te pasa una",
    "tabla de",
    "conversion y",
    "te pide que",
    "le eches una",
    "mano a ",
    "decodificar un",
    "mensaje. ",
    "             ",
    "             ",
    "No tienen la",
    "tabla completa,"
    "asi que tienes"
    "que echar mano",
    "de tus",
    "conocimientos en",
    "criptografia",
    "para ",
    "descifrar el",
    "error oculto",
    "en el codigo.",
    "             ",
    "             ",
    "Como pago por",
    "el trabajo, ",
    "te dara un ",
    "add-on para",
    "tu badge.",
    "Y un codigo",
    "para la matrix."};

char* mission_two_ywhack_beacon_description[MISSION_TWO_YWHACK_DESCR] = {
    "Esto es un reto",
    "no? ...",
    "Debemos ganar,",
    "YES WE HACK!!",
    "Que interesante",
    "esto de hackear",
    "no?",
    "Tal vez decirlo",
    "nos otorgue",
    "poderes",
    "o addons",
    "             ",
    "             ",
    "             ",
    "             ",
    "     Espera!    ",
    "Oh los gatos!",
    "a los gatos",
    "les gustan",
    "los addons",
    "si tienes",
    "uno tal vez"
    "les guste",
    "verlo"};

// No encrypted
char* mission_two_description[MISSION_TWO_DESCRIPTION] = {
    "... El saludo",  "secreto de la",  "gente de",         "Yes We Hack",
    "             ",  "             ",  "El saludo es",     "tan sencillo",
    "como gritar...", "             ",  "YES WE HACK!",     "             ",
    "al llegar a su", "villa, asi que", "grita lo mas",     "fuerte que",
    "puedas!",        "             ",  "- NUEVA MISION -",
};

char* mission_two_ec_beacon_hacked[MISSION_TWO_EC_HACKED_BEACON] = {
    "... en el ",
    "stand de les",
    "gatos, ",
    "todes maullan",
    "...",
    "             ",
    "             ",
    "No es broma, ",
    "se ha convertido",
    "en una costumbre.",
    "Les eCats se",
    "han envilecido",
    "y ahora maullan",
    "como si de",
    "verdad fueran",
    "mascotas peludas.",
    "Te acercas y te",
    "preguntas como",
    "puedes",
    "comunicarte",
    "con elles."
    "             ",
    "             ",
    "Recuerdas aquel",
    "gato que vivía",
    "en casa de tu",
    "abuela.",
    "Al acariciarle",
    "tras de las",
    "orejas, ",
    "ronroneaba.",
    "Quizás si te",
    "acercas en modo",
    "ronroneante,",
    "consigas algo",
    "de elles."
    "             ",
    "             ",
    "- Prrrr,",
    "prrrrmiiiaaauuu",
    "- dices primero",
    "tímidamente y",
    "luego repites",
    "cada vez más",
    "alto...",
    "             ",
    "             ",
    "Uno de los",
    "eCats gira su",
    "cabeza,",
    "olisquea el ",
    "aire y te ",
    "maulla ",
    "sonriente:",
    "             ",
    "             ",
    "- Miiiiiaaauuu",
    "prrr, prrr."
    "             ",
    "             ",
    "Mira tu badge,",
    "que llevas ",
    "colgado del ",
    "cuello, ",
    "lo manipula, ",
    "ve el add-on ",
    "y con un ",
    "marcatextos, ",
    "te escribe",
    "algo en la",
    "palma de la ",
    "mano.",
    "Tu siques ",
    "estando absorto",
    "en ver a une",
    "adulte maullar",
    "al unísono con",
    "otres, pero ya",
    "tienes lo que",
    "quieres y estas",
    "listo para",
    "marchar",
    "cuando ...",
    "             ",
    "             ",
    "... une tipe",
    "con barba te",
    "esta diciendo",
    "algo al oido ...",
    "... no lo oyes",
    "bien, respondes",
    "con un -miau-",
    "porque tienes",
    "miedo de romper",
    "la magia y que",
    "le extra\32e se",
    "marche sin",
    "enterarte el",
    "mensaje.",
    "Después de",
    "un par de",
    "repecitiones",
    "...",
    "             ",
    "             ",
    "- No seas",
    "idiote!",
    "No soy un gato!",
    "- exclama",
    "- Perdon, como",
    "lo iba yo",
    "a saber?",
    "Pero es que",
    "tanto maullar",
    "se me olvidan",
    "las cosas",
    "             ",
    "- El tipe con",
    "barba te dice..",
    "             ",
    "Toma este",
    "codigo, te",
    "sera util",
    "             ",
};

char* mission_two_ec_beacon[MISSION_TWO_EC_BEACON] = {
    "... en el ",
    "stand de los",
    "gatos, ",
    "todos maullan",
    "...",
    "             ",
    "             ",
    "No es broma, ",
    "se ha convertido",
    "en una costumbre.",
    "Los eCats se",
    "han envilecido",
    "y ahora maullan",
    "como si de",
    "verdad fueran",
    "mascotas peludas.",
    "Te acercas y te",
    "preguntas como",
    "puedes",
    "comunicarte",
    "con ellos."
    "             ",
    "             ",
    "Recuerdas aquel",
    "gato que vivía",
    "en casa de tu",
    "abuela.",
    "Al acariciarle",
    "tras de las",
    "orejas, ",
    "ronroneaba.",
    "Quizás si te",
    "acercas en modo",
    "ronroneante,",
    "consigas algo",
    "de ellos."
    "             ",
    "             ",
    "- Prrrr,",
    "prrrrmiiiaaauuu",
    "- dices primero",
    "tímidamente y",
    "luego repites",
    "cada vez más",
    "alto...",
    "             ",
    "             ",
    "Uno de los",
    "eCats gira su",
    "cabeza,",
    "olisquea el ",
    "aire y te ",
    "maulla ",
    "sonriente:",
    "             ",
    "             ",
    "- Miiiiiaaauuu",
    "prrr, prrr."
    "             ",
    "             ",
    "Mira tu badge,",
    "que llevas ",
    "colgado del ",
    "cuello, ",
    "lo manipula, ",
    "ve el add-on ",
    "y con un ",
    "marcatextos, ",
    "te escribe",
    "algo en la",
    "palma de la ",
    "mano.",
    "Tu siques ",
    "estando absorto",
    "en ver a une",
    "adulto maullar",
    "al unísono con",
    "otros, pero ya",
    "tienes lo que",
    "quieres y estas",
    "listo para",
    "marchar",
    "cuando ...",
    "             ",
    "             ",
    "... un tipo",
    "con barba te",
    "esta diciendo",
    "algo al oido ...",
    "... no lo oyes",
    "bien, respondes",
    "con un -miau-",
    "porque tienes",
    "miedo de romper",
    "la magia y que",
    "le extra\32e se",
    "marche sin",
    "enterarte el",
    "mensaje.",
    "Después de",
    "un par de",
    "repecitiones",
    "...",
    "             ",
    "             ",
    "- No seas",
    "idiota!",
    "No soy un gato!",
    "- exclama",
    "- Perdon, como",
    "lo iba yo",
    "a saber?",
    "Pero es que",
    "tanto maullar",
    "se me olvidan",
    "las cosas",
    "             ",
    "- El tipo con",
    "barba te dice..",
    "             ",
    "Toma este",
    "codigo, te",
    "sera util",
    "             ",
};

// Line two EC start
char* mission_two_ec_beacon_start[MISSION_TWO_EC_MISSION_AS] = {
    "Dicen que",       "a los gatos",     "les gusta",       "el pescado",
    "pero lo",         "cierto es",       "que tambien",     "disfrutan de",
    "un asado...",     "             ",   "             ",   "Te acercas a",
    "villa y vez",     "a un grupo",      "lleno de",        "dispositivos",
    "electronicos",    "que parecen",     "gatos...",        "             ",
    "             ",   "Te preguntas -",  "Que hacen",       "aqui? -",
    "             ",   "Cuando lo que",   "parece un gato",  "naranja se",
    "acerca y te",     "pregunta -",      "Miau?",           "             ",
    "             ",   "Tu le respondes", "con un -Miau-",   "y el gato",
    "naranja te",      "dice -",          "Traes el asado?", "             ",
    "             ",   "Confundido,",     "le respondes",    "con un -Miau-",
    "y el gato",       "naranja te",      "dice -",          "No eres de",
    "aqui, verdad?",   "             ",   "             ",   "Tu le respondes",
    "con un -Miau-",   "y el gato",       "naranja te",      "dice -",
    "No te preocupes", "por eso,",        "aqui todos",      "son bienvenidos.",
    "             ",   "Para mostrarte",  "nuestros",        "dispositivos,",
    "requerimos",      "que hagas algo",  "por nosotros...", "             ",
    "             ",   "Consigue un",     "poco de asado",   "y te mostraremos",
    "nuestros",        "dispositivos...", "             ",   "- Nueva Mision -",
};

char* mission_two_ec_description[MISSION_TWO_EC_DESCRIPTION] = {
    "Los gatos",     "quieren",     "asado",         "             ",
    "             ", "Consigue un", "poco de asado", "para ver los",
    "dispositivos",  "de la villa", "de los gatos",  "             ",
};

char* mission_two_asado_beacon[MISSION_TWO_EC_ASA_BEACON] = {
    "Comienza a ",    "sonar una",       "melodia...",    "             ",
    "             ",  "Azul, y es",      "que este amor", "es azul, como",
    "el mar azul...", "             ",   "             ", "Confundido",
    "por la melodia", "pero con",        "hambre,",       "te preguntas",
    "que es ese",     "olor a asado?",   "             ", "Huele bien...",
    "- Piensas -",    "             ",   "Cuando se te",  "acerca un",
    "se\361or",       "y te dice -",     "             ", "             ",
    "- Hola,",        "estas buscando",  "algo?",         "             ",
    "             ",  "No logras",       "enfocarte",     "el olor es",
    "demasiado...",   "             ",   "- Veo que",     "no puedes",
    "enfocarte,",     "te puedo",        "ayudar?",       "             ",
    "             ",  "Tu le respondes", "con un -Miau-", "y el se\361or",
    "te dice -",      "             ",   "             ", "- Ahora",
    "entiendo,",      "los gatos",       "tienen hambre", "...",
    "             ",  "             ",   "Toma este",     "codigo para",
    "la matrix ...",  "             ",
};

char* mission_two_asado_beacon_hacked[MISSION_TWO_EC_ASA_BEACON_HACKED] = {
    "Comienza a ",    "sonar una",       "melodia...",    "             ",
    "             ",  "Azul, y es",      "que este amor", "es azul, como",
    "el mar azul...", "             ",   "             ", "Confundido",
    "por la melodia", "pero con",        "hambre,",       "te preguntas",
    "que es ese",     "olor a asado?",   "             ", "Huele bien...",
    "- Piensas -",    "             ",   "Cuando se te",  "acerca un",
    "se\361er",       "y te dice -",     "             ", "             ",
    "- Hola,",        "estas buscando",  "algo?",         "             ",
    "             ",  "No logras",       "enfocarte",     "el olor es",
    "demasiado...",   "             ",   "- Veo que",     "no puedes",
    "enfocarte,",     "te puedo",        "ayudar?",       "             ",
    "             ",  "Tu le respondes", "con un -Miau-", "y el se\361er",
    "te dice -",      "             ",   "             ", "- Ahora",
    "entiendo,",      "les getes",       "tienen hambre", "...",
    "             ",  "             ",   "Toma este",     "codigo para",
    "la matrix ...",  "             ",
};

char* mission_two_ec_beacon_complete[MISSION_TWO_EC_ASA_DESCR] = {
    "Vez a un gato", "que se pone",   "feliz...",      "             ",
    "             ", "El gato",       "empieza a",     "comer el ",
    "asado...",      "             ", "             ", "Y te dice -",
    "Toma este",     "codigo para",   "la matrix ...",
};

uint8_t mission_hacked_active();
void mission_two_begin(uint8_t village_idx);
void mission_two_hacked_begin(uint8_t village_idx);
void mission_two_unhack_animation();
void mission_two_show_mission_details(void* exit_cb);